### ISSUE TITLE
paper heigth is too short

### ISSUE THREAD

**Issue by HilalTAN** [kaanakyalcin/wise_bluetooth_print#5]
We try the code with the SPP-ML310 Bixolon printer. Although the page size is not given as a parameter, it outputs approximately 3-4 cm. Output size normally needs to be 10-15 cm.

**Comment by kaanakyalcin** [comment]
It is not related to the package. It is related to the parameter that you sent as 'printText'.
For example, the sample code uses ZPL language to print.

String printTextZPL = "^XA"
        "^LH55,30"
        "^FO20,10^CFD,27,13^FDCompany Name^FS"
        "^FO20,60^AD^FD<DESCRIPTION >^FS"
        "^FO40,160^BY2,2.0^BCN,100,Y,N,N,N^FD<PART,-1>^FS"
        "^XZ";

The LH part defines paper sizes like 55, 30.

**Comment by HilalTAN** [comment]
![WhatsApp Image 2023-07-18 at 17 06 47](https://github.com/kaanakyalcin/wise_bluetooth_print/assets/107698568/909d66c4-7182-4bea-a8d7-675b25ae8917)

hi. I have used this package before. there was no problem before. now i am having the problem appearing in the file. can you please help.
